version: '3.8'
services:
  frontend:
    image: frontend_angular:latest
    container_name: angular_frontend
    ports:
      - '30001:80'
    environment:
      - API_URL=http://appTerritory:8080
    networks:
      - redeTeste

  mysql:
    image: mysql:8.0-debian
    container_name: mysqlTerritory
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: territory
    ports:
      - "3307:3306"
    networks:
      - redeTeste
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: territory:v2  # substitua com o nome correto da sua imagem, se necessário
    container_name: appTerritory
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlTerritory:3306/territory
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      CORS_URL: http://localhost:30001
    networks:
      - redeTeste
    restart: on-failure

networks:
  redeTeste:
    driver: bridge
