version: '3.8'
services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysqlTerritory
    environment:
      MYSQL_ROOT_PASSWORD: root   # Define a senha do usuário root
      MYSQL_DATABASE: territory 
    ports:
      - "3307:3306"
    networks:
      - redeTeste
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: territory:latest # substitua com o nome correto da sua imagem, se necessário
    container_name: appTerritory
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlTerritory:3306/territory
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - redeTeste
    restart: on-failure # reinicia o container se ele falhar

networks:
  redeTeste:
    driver: bridge
