apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app  # Nome do seu Deployment
  minReplicas: 1
  maxReplicas: 10  # Número máximo de réplicas
  targetCPUUtilizationPercentage: 50  # A utilização de CPU alvo
