apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: v2.54.1
    helm.sh/chart: prometheus-25.27.0
  name: prometheus-server
  namespace: default
spec:
  clusterIP: 10.101.104.30
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: default
spec:
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: {}
  scrapeInterval: 30s
  resources:
    requests:
      memory: 400Mi
  ruleSelector: {}
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: default
      port: web
  scrapeConfigs:
    - job_name: 'your-application'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['192.168.49.2:8080']  # Verifique se o IP e a porta estão corretos

    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
